[build]
  # Define o diretório onde o Netlify deve buscar os arquivos estáticos (HTML, CSS, JS)
  publish = "Caminho do seu index.html"

[functions]
  # Define o diretório onde o Netlify deve buscar as funções serverless
  directory = "netlify/functions"
  # Define o tempo limite padrão para todas as funções (30 segundos)
  timeout = 30
```eof
