[build]
  # O seu index.html, style.css e script.js estão na raiz do repositório.
  # O Netlify deve publicar o diretório raiz.
  publish = "/"

[functions]
  # O diretório 'netlify/functions' está na raiz do repositório.
  directory = "netlify/functions"
  # Define o tempo limite padrão para todas as funções (30 segundos)
  timeout = 30
