[build]
  functions = "netlify/functions"  # Pasta das funções (caso você as use)
  publish = "."                    # Ponto indica a raiz do repositório

[functions]
  node_bundler = "esbuild"
  node_runtime = "nodejs20.x"
